//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivCloud_Datos.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public string Telephone { get; set; }
        public string Image { get; set; }
    }
}
