//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivCloud_Datos.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor_Subject
    {
        public string ID { get; set; }
        public string Professor { get; set; }
        public string Subject { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
