//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivCloud_Datos.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules_Assigneds
    {
        public int ID_Schedule { get; set; }
        public string Code_Schedule { get; set; }
        public Nullable<System.TimeSpan> HourStart { get; set; }
        public Nullable<System.TimeSpan> HourEnd { get; set; }
        public string Day { get; set; }
        public string Name { get; set; }
        public string Code_Employee { get; set; }
        public string LastName { get; set; }
        public string Subject { get; set; }
        public string Classroom_Assigned { get; set; }
    }
}
