//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivCloud_Datos.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Schedule_Professor = new HashSet<Schedule_Professor>();
        }
    
        public string Code_Schedule { get; set; }
        public Nullable<System.TimeSpan> HourStart { get; set; }
        public Nullable<System.TimeSpan> HourEnd { get; set; }
        public string Day { get; set; }
        public string Subject { get; set; }
        public string Classroom { get; set; }
    
        public virtual Classroom Classroom1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_Professor> Schedule_Professor { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
