//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivCloud_Datos.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Record_Maintenance = new HashSet<Record_Maintenance>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public int Privilege { get; set; }
        public string Employee { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Privileges Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record_Maintenance> Record_Maintenance { get; set; }
    }
}
